# Generated by Django 4.2.16 on 2025-11-23 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0012_member_blood_type_member_height_member_weight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberPaymentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_day', models.IntegerField(choices=[(15, 'Día 15'), (30, 'Día 30')])),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_profile', to='crm.member')),
            ],
        ),
    ]
