# Generated by Django 4.2.16 on 2025-11-28 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberpaymentprofile',
            options={'verbose_name': 'Member Payment Profile', 'verbose_name_plural': 'Member Payment Profiles'},
        ),
        migrations.AlterField(
            model_name='memberpaymentprofile',
            name='due_day',
            field=models.IntegerField(choices=[(15, 'Día 15'), (30, 'Día 30')], verbose_name='Due Day'),
        ),
        migrations.AlterField(
            model_name='memberpaymentprofile',
            name='monthly_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='monthly fee'),
        ),
    ]
