# Generated by Django 4.2.16 on 2025-11-25 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last name')),
                ('second_last_name', models.CharField(max_length=255, verbose_name='Second last name')),
                ('curp', models.CharField(max_length=18)),
                ('birth_date', models.DateField(verbose_name='Birth date')),
                ('address', models.TextField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, verbose_name='Gender')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email address')),
                ('photo', models.ImageField(upload_to='members_photos/', verbose_name='Photo')),
                ('how_did_you_hear_details', models.CharField(blank=True, help_text='Provide more details about how you heard about the academy.', max_length=255, null=True, verbose_name='Additional details')),
                ('medical_condition_details', models.CharField(blank=True, max_length=255, null=True, verbose_name='Medical condition details')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Weight (kg)')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Height (m)')),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True)),
                ('folio', models.CharField(blank=True, editable=False, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('accept_terms', models.BooleanField(default=False, verbose_name='Accepted Terms and Conditions')),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('DONE', 'Done'), ('CANCELED', 'Canceled')], default='PENDING', max_length=10, verbose_name='approval status')),
                ('how_did_you_hear', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.discoverysource', verbose_name='How did you hear about us?')),
                ('medical_conditions', models.ManyToManyField(blank=True, to='crm.medicalcondition')),
                ('member', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preregister', to='crm.member')),
            ],
            options={
                'verbose_name': 'Pre-register',
                'verbose_name_plural': 'Pre-registers',
            },
        ),
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Términos y Condiciones', max_length=255)),
                ('pdf', models.FileField(upload_to='terms_and_conditions/')),
            ],
            options={
                'verbose_name': 'Terms and Conditions',
                'verbose_name_plural': 'Terms and Conditions',
            },
        ),
        migrations.CreateModel(
            name='PreRegisterContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone number')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Primary contact')),
                ('is_emergency', models.BooleanField(default=False, verbose_name='Emergency contact')),
                ('preregister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preregisters', to='preregistration.preregister')),
                ('relation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.contactrelation', verbose_name='Relation')),
            ],
            options={
                'verbose_name': 'Pre-register Contact',
                'verbose_name_plural': 'Pre-register Contacts',
            },
        ),
        migrations.AddConstraint(
            model_name='preregistercontact',
            constraint=models.UniqueConstraint(fields=('preregister', 'phone_number'), name='unique_preregister_contact_phone'),
        ),
    ]
