# Generated by Django 4.2.16 on 2024-11-22 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_rename_customer_memberaccesslog_member'),
        ('preregistration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preregister',
            name='how_did_you_hear',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preregisters', to='crm.discoverysource'),
        ),
    ]
