# Generated by Django 4.2.16 on 2025-11-28 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preregistration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preregister',
            name='address',
            field=models.TextField(verbose_name='Address'),
        ),
    ]
