# Generated by Django 4.2.16 on 2024-11-27 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_member_how_did_you_hear'),
        ('preregistration', '0003_alter_preregister_folio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preregister',
            name='curp',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='preregister',
            name='how_did_you_hear',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.discoverysource'),
        ),
    ]
