# Generated by Django 4.2.16 on 2024-11-27 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_medicalcondition_member_medical_comdition_details_and_more'),
        ('preregistration', '0004_alter_preregister_curp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preregister',
            name='medical_comdition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.medicalcondition'),
        ),
        migrations.AddField(
            model_name='preregister',
            name='medical_comdition_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
