# Generated by Django 4.2.16 on 2024-11-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preregistration', '0006_rename_medical_comdition_preregister_medical_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preregister',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DONE', 'Done'), ('CANCELED', 'Canceled')], default='PENDING', max_length=10, verbose_name='approval status'),
        ),
    ]
