# Generated by Django 4.2.16 on 2024-11-28 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_contactrelation_alter_membercontact_relation'),
        ('preregistration', '0007_preregister_approval_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreRegisterContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_emergency', models.BooleanField(default=False)),
                ('preregister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preregisters', to='preregistration.preregister')),
                ('relation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.contactrelation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
