# Generated by Django 4.2.16 on 2024-12-04 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preregistration', '0008_preregistercontact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preregister',
            name='has_allergy',
        ),
        migrations.RemoveField(
            model_name='preregister',
            name='has_flat_feet',
        ),
        migrations.RemoveField(
            model_name='preregister',
            name='has_heart_conditions',
        ),
        migrations.RemoveField(
            model_name='preregister',
            name='has_illness',
        ),
        migrations.RemoveField(
            model_name='preregister',
            name='medical_condition',
        ),
    ]
