# Generated by Django 4.2.16 on 2024-12-11 02:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_member_last_name_member_second_last_name'),
        ('preregistration', '0010_preregister_medical_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='preregister',
            name='accept_terms',
            field=models.BooleanField(default=False, verbose_name='Accepted Terms and Conditions'),
        ),
        migrations.AddField(
            model_name='preregister',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preregister',
            name='last_name',
            field=models.CharField(default='lastname', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preregister',
            name='second_last_name',
            field=models.CharField(default='lastname2', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preregister',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preregister', to='crm.member'),
        ),
    ]
