# Generated by Django 4.2.16 on 2024-12-11 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_member_last_name_member_second_last_name'),
        ('preregistration', '0011_preregister_accept_terms_preregister_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preregister',
            name='member',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preregister', to='crm.member'),
        ),
    ]
