# Generated by Django 4.2.17 on 2024-12-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preregistration', '0012_alter_preregister_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Términos y Condiciones', max_length=255)),
                ('pdf', models.FileField(upload_to='terms_and_conditions/')),
            ],
        ),
    ]
