# Generated by Django 4.2.16 on 2025-09-23 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preregistration', '0013_termsandconditions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preregister',
            options={'verbose_name': 'Pre-register', 'verbose_name_plural': 'Pre-registers'},
        ),
        migrations.AlterModelOptions(
            name='preregistercontact',
            options={'verbose_name': 'Pre-register Contact', 'verbose_name_plural': 'Pre-register Contacts'},
        ),
        migrations.AlterModelOptions(
            name='termsandconditions',
            options={'verbose_name': 'Terms and Conditions', 'verbose_name_plural': 'Terms and Conditions'},
        ),
    ]
