# Generated by Django 4.2.16 on 2025-11-10 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preregistration', '0014_alter_preregister_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preregister',
            name='address',
            field=models.TextField(default='sin direccion', verbose_name='Dirección Completa'),
            preserve_default=False,
        ),
    ]
