# Generated by Django 4.2.16 on 2025-11-14 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preregistration', '0015_preregister_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='preregister',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='preregister',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Height (m)'),
        ),
        migrations.AddField(
            model_name='preregister',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Weight (kg)'),
        ),
        migrations.AlterField(
            model_name='preregister',
            name='address',
            field=models.TextField(),
        ),
    ]
