# Generated by Django 4.2.16 on 2025-10-15 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_alter_member_birth_date_alter_member_email_and_more'),
        ('preregistration', '0015_alter_preregister_last_name_alter_preregister_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preregister',
            name='birth_date',
            field=models.DateField(verbose_name='Birth date'),
        ),
        migrations.AlterField(
            model_name='preregister',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='preregister',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='preregister',
            name='how_did_you_hear',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.discoverysource', verbose_name='How did you hear about us?'),
        ),
        migrations.AlterField(
            model_name='preregister',
            name='how_did_you_hear_details',
            field=models.CharField(blank=True, help_text='Provide more details about how you heard about the academy.', max_length=255, null=True, verbose_name='Additional details'),
        ),
        migrations.AlterField(
            model_name='preregister',
            name='medical_condition_details',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Medical condition details'),
        ),
        migrations.AlterField(
            model_name='preregister',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='preregister',
            name='photo',
            field=models.ImageField(upload_to='members_photos/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='preregister',
            name='second_last_name',
            field=models.CharField(max_length=255, verbose_name='Second last name'),
        ),
        migrations.AlterField(
            model_name='preregistercontact',
            name='is_emergency',
            field=models.BooleanField(default=False, verbose_name='Emergency contact'),
        ),
        migrations.AlterField(
            model_name='preregistercontact',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Primary contact'),
        ),
        migrations.AlterField(
            model_name='preregistercontact',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='preregistercontact',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='preregistercontact',
            name='relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.contactrelation', verbose_name='Relation'),
        ),
    ]
