# Generated by Django 4.2.16 on 2025-11-23 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preregistration', '0016_preregister_blood_type_preregister_height_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='preregistercontact',
            constraint=models.UniqueConstraint(fields=('preregister', 'phone_number'), name='unique_preregister_contact_phone'),
        ),
    ]
