# Generated by Django 4.2.16 on 2024-11-19 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def create_default_statuses(apps, schema_editor):
    # Obtener el modelo ClientStatus
    AccessStatus = apps.get_model("crm", "AccessStatus")

    # Lista de estatus predeterminados
    default_statuses = ["Activo", "Inactivo"]

    # Crear los estatus si no existen
    for status_name in default_statuses:
        AccessStatus.objects.get_or_create(name=status_name)

def create_default_discovery_source(apps, schema_editor):
    # Obtener el modelo DiscoverySource
    DiscoverySource = apps.get_model('crm', 'DiscoverySource')
    
    # Crear el registro "other" si no existe
    DiscoverySource.objects.get_or_create(name="other")

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Status Name')),
            ],
            options={
                'verbose_name': 'Access Status',
                'verbose_name_plural': 'Access Statuses',
            },
        ),
        migrations.CreateModel(
            name='DiscoverySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Source Name')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('curp', models.CharField(max_length=18, unique=True)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(upload_to='members_photos/')),
                ('how_did_you_hear_details', models.CharField(blank=True, max_length=255, null=True)),
                ('has_illness', models.BooleanField(default=False, verbose_name='Has any illness')),
                ('has_allergy', models.BooleanField(default=False, verbose_name='Has any allergy')),
                ('has_flat_feet', models.BooleanField(default=False, verbose_name='Has flat feet')),
                ('has_heart_conditions', models.BooleanField(default=False, verbose_name='Has heart conditions')),
                ('how_did_you_hear', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_sources', to='crm.discoverysource')),
            ],
        ),
        migrations.CreateModel(
            name='MemberContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('relation', models.CharField(max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_emergency', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.member')),
            ],
        ),
        migrations.CreateModel(
            name='MemberAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('date_changed', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='crm.member')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_statuses', to='crm.accessstatus')),
            ],
        ),
        migrations.RunPython(create_default_statuses),
        migrations.RunPython(create_default_discovery_source),
    ]
