# Generated by Django 4.2.16 on 2025-11-25 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Status Name')),
            ],
            options={
                'verbose_name': 'Access Status',
                'verbose_name_plural': 'Access Statuses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AgeSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Segment Name')),
                ('min_age', models.PositiveIntegerField(help_text='Minimum age for this segment in years.', verbose_name='Minimum Age')),
                ('max_age', models.PositiveIntegerField(help_text='Maximum age for this segment in years.', verbose_name='Maximum Age')),
            ],
            options={
                'verbose_name': 'Age Segment',
                'verbose_name_plural': 'Age Segments',
                'ordering': ['min_age'],
            },
        ),
        migrations.CreateModel(
            name='ContactRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Relation Name')),
            ],
            options={
                'verbose_name': 'Contact Relation',
                'verbose_name_plural': 'Contact Relations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DiscoverySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Source Name')),
            ],
            options={
                'verbose_name': 'Discovery Source',
                'verbose_name_plural': 'Discovery Sources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MedicalCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Condition Name')),
            ],
            options={
                'verbose_name': 'Medical Condition',
                'verbose_name_plural': 'Medical Conditions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last name')),
                ('second_last_name', models.CharField(max_length=255, verbose_name='Second last name')),
                ('birth_date', models.DateField(verbose_name='Birth date')),
                ('address', models.TextField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, verbose_name='Gender')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email address')),
                ('photo', models.ImageField(upload_to='members_photos/', verbose_name='Photo')),
                ('how_did_you_hear_details', models.CharField(blank=True, help_text='Provide more details about how you heard about the academy.', max_length=255, null=True, verbose_name='Additional details')),
                ('medical_condition_details', models.CharField(blank=True, max_length=255, null=True, verbose_name='Medical condition details')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Weight (kg)')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Height (m)')),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True)),
                ('member_code', models.CharField(max_length=100, unique=True, verbose_name='Member code')),
                ('enrollment_date', models.DateField(auto_now_add=True, verbose_name='Enrollment date')),
                ('curp', models.CharField(max_length=18, unique=True)),
                ('how_did_you_hear', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.discoverysource', verbose_name='How did you hear about us?')),
                ('medical_conditions', models.ManyToManyField(blank=True, to='crm.medicalcondition', verbose_name='Medical conditions')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'ordering': ['member_code'],
            },
        ),
        migrations.CreateModel(
            name='MemberContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone number')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Primary contact')),
                ('is_emergency', models.BooleanField(default=False, verbose_name='Emergency contact')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.member')),
                ('relation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.contactrelation', verbose_name='Relation')),
            ],
            options={
                'verbose_name': 'Member Contact',
                'verbose_name_plural': 'Member Contacts',
                'ordering': ['member', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MemberAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255, verbose_name='Reason')),
                ('date_changed', models.DateTimeField(auto_now_add=True, verbose_name='Date changed')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Changed by')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='crm.member', verbose_name='Member')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_statuses', to='crm.accessstatus', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Member Access Log',
                'verbose_name_plural': 'Member Access Logs',
                'ordering': ['-date_changed'],
            },
        ),
        migrations.AddConstraint(
            model_name='membercontact',
            constraint=models.UniqueConstraint(fields=('member', 'phone_number'), name='unique_member_contact_phone'),
        ),
    ]
