# Generated by Django 4.2.16 on 2024-11-19 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberaccesslog',
            old_name='customer',
            new_name='member',
        ),
    ]
