# Generated by Django 4.2.16 on 2024-11-27 02:09

from django.db import migrations, models

def create_default_age_segments(apps, schema_editor):
    """Create default age segments."""
    AgeSegment = apps.get_model('crm', 'AgeSegment')  # Obtener el modelo dinámicamente
    default_segments = [
        {"name": "Baby", "min_age": 1, "max_age": 2},
        {"name": "Child", "min_age": 2, "max_age": 18},
        {"name": "Adult", "min_age": 18, "max_age": 60},
        {"name": "Senior", "min_age": 60, "max_age": 100},
    ]

    for segment in default_segments:
        AgeSegment.objects.create(**segment)

class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_rename_customer_memberaccesslog_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Segment Name')),
                ('min_age', models.PositiveIntegerField(help_text='Minimum age for this segment in years.', verbose_name='Minimum Age')),
                ('max_age', models.PositiveIntegerField(help_text='Maximum age for this segment in years.', verbose_name='Maximum Age')),
            ],
            options={
                'verbose_name': 'Age Segment',
                'verbose_name_plural': 'Age Segments',
                'ordering': ['min_age'],
            },
        ),
        migrations.RunPython(create_default_age_segments),  # Agregar datos iniciales

    ]
