# Generated by Django 4.2.16 on 2025-11-28 03:12

from django.db import migrations

def create_required_initial_data(apps, schema_editor):
    AccessStatus = apps.get_model('crm', 'AccessStatus')
    MedicalCondition = apps.get_model('crm', 'MedicalCondition')
    ContactRelation = apps.get_model('crm', 'ContactRelation')
    AgeSegment = apps.get_model('crm', 'AgeSegment')
    DiscoverySource = apps.get_model('crm', 'DiscoverySource')

    # --- AccessStatus (requeridos) ---
    required_statuses = ["Activo", "Inactivo"]
    for status in required_statuses:
        AccessStatus.objects.get_or_create(name=status)

    # --- MedicalCondition (requerido por tu lógica de carga) ---
    MedicalCondition.objects.get_or_create(name="Ninguna")
    MedicalCondition.objects.get_or_create(name="Otra")

    # --- ContactRelation (recomendados) ---
    relations = ["Padre", "Madre", "Tutor"]
    for rel in relations:
        ContactRelation.objects.get_or_create(name=rel)

    # --- AgeSegment (rangos recomendados) ---
    age_segments = [
        ("Bebé", 0, 3),
        ("Niño", 3, 12),
        ("Adolescente", 12, 18),
        ("Adulto", 18, 60),
        ("Adulto mayor", 60, 100),
    ]

    for name, min_age, max_age in age_segments:
        AgeSegment.objects.get_or_create(
            name=name,
            defaults={"min_age": min_age, "max_age": max_age},
        )
    # --- DiscoverySource (requeridos) ---
    sources = ["Referencia personal", "Otra"]
    for src in sources:
        DiscoverySource.objects.get_or_create(name=src)

class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_member_address'),
    ]

    operations = [
        migrations.RunPython(create_required_initial_data),
    ]
