# Generated by Django 4.2.16 on 2024-11-27 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_agesegment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='how_did_you_hear',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.discoverysource'),
        ),
    ]
