# Generated by Django 4.2.16 on 2024-11-27 06:01

from django.db import migrations, models
import django.db.models.deletion

def create_default_medical_conditions(apps, schema_editor):
    # Obtener el modelo MedicalCondition
    MedicalCondition = apps.get_model('crm', 'MedicalCondition')
    
    # Crear los registros "other" y "None" si no existen
    MedicalCondition.objects.get_or_create(name="other")
    MedicalCondition.objects.get_or_create(name="None")

class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_member_how_did_you_hear'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Condition Name')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='medical_comdition_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='medical_comdition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.medicalcondition'),
        ),
        migrations.RunPython(create_default_medical_conditions),
    ]
