# Generated by Django 4.2.16 on 2024-12-04 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_contactrelation_alter_membercontact_relation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='has_allergy',
        ),
        migrations.RemoveField(
            model_name='member',
            name='has_flat_feet',
        ),
        migrations.RemoveField(
            model_name='member',
            name='has_heart_conditions',
        ),
        migrations.RemoveField(
            model_name='member',
            name='has_illness',
        ),
        migrations.RemoveField(
            model_name='member',
            name='medical_condition',
        ),
        migrations.AddField(
            model_name='member',
            name='medical_conditions',
            field=models.ManyToManyField(blank=True, to='crm.medicalcondition'),
        ),
    ]
