# Generated by Django 4.2.16 on 2024-12-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_remove_member_has_allergy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='last_name',
            field=models.CharField(default='lasname', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='second_last_name',
            field=models.CharField(default='lastname2', max_length=255),
            preserve_default=False,
        ),
    ]
