# Generated by Django 4.2.16 on 2025-09-23 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_member_last_name_member_second_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessstatus',
            options={'ordering': ['name'], 'verbose_name': 'Access Status', 'verbose_name_plural': 'Access Statuses'},
        ),
        migrations.AlterModelOptions(
            name='contactrelation',
            options={'ordering': ['name'], 'verbose_name': 'Contact Relation', 'verbose_name_plural': 'Contact Relations'},
        ),
        migrations.AlterModelOptions(
            name='discoverysource',
            options={'ordering': ['name'], 'verbose_name': 'Discovery Source', 'verbose_name_plural': 'Discovery Sources'},
        ),
        migrations.AlterModelOptions(
            name='medicalcondition',
            options={'ordering': ['name'], 'verbose_name': 'Medical Condition', 'verbose_name_plural': 'Medical Conditions'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['member_code'], 'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
        migrations.AlterModelOptions(
            name='memberaccesslog',
            options={'ordering': ['-date_changed'], 'verbose_name': 'Member Access Log', 'verbose_name_plural': 'Member Access Logs'},
        ),
        migrations.AlterModelOptions(
            name='membercontact',
            options={'ordering': ['member', 'name'], 'verbose_name': 'Member Contact', 'verbose_name_plural': 'Member Contacts'},
        ),
    ]
