# Generated by Django 4.2.16 on 2025-11-04 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_alter_accessstatus_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.TextField(default='Ingresa tu dirección', verbose_name='Dirección Completa'),
            preserve_default=False,
        ),
    ]
