# Generated by Django 4.2.16 on 2025-10-06 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_alter_accessstatus_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=255, verbose_name='First name'),
        ),
    ]
