# Generated by Django 4.2.16 on 2025-10-15 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0011_alter_member_last_name_alter_member_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='birth_date',
            field=models.DateField(verbose_name='Birth date'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='member',
            name='enrollment_date',
            field=models.DateField(auto_now_add=True, verbose_name='Enrollment date'),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='member',
            name='how_did_you_hear',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.discoverysource', verbose_name='How did you hear about us?'),
        ),
        migrations.AlterField(
            model_name='member',
            name='how_did_you_hear_details',
            field=models.CharField(blank=True, help_text='Provide more details about how you heard about the academy.', max_length=255, null=True, verbose_name='Additional details'),
        ),
        migrations.AlterField(
            model_name='member',
            name='medical_condition_details',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Medical condition details'),
        ),
        migrations.AlterField(
            model_name='member',
            name='medical_conditions',
            field=models.ManyToManyField(blank=True, to='crm.medicalcondition', verbose_name='Medical conditions'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_code',
            field=models.CharField(max_length=100, unique=True, verbose_name='Member code'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(upload_to='members_photos/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='member',
            name='second_last_name',
            field=models.CharField(max_length=255, verbose_name='Second last name'),
        ),
        migrations.AlterField(
            model_name='memberaccesslog',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Changed by'),
        ),
        migrations.AlterField(
            model_name='memberaccesslog',
            name='date_changed',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date changed'),
        ),
        migrations.AlterField(
            model_name='memberaccesslog',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='crm.member', verbose_name='Member'),
        ),
        migrations.AlterField(
            model_name='memberaccesslog',
            name='reason',
            field=models.CharField(max_length=255, verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='memberaccesslog',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_statuses', to='crm.accessstatus', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='membercontact',
            name='is_emergency',
            field=models.BooleanField(default=False, verbose_name='Emergency contact'),
        ),
        migrations.AlterField(
            model_name='membercontact',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Primary contact'),
        ),
        migrations.AlterField(
            model_name='membercontact',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='membercontact',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='membercontact',
            name='relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.contactrelation', verbose_name='Relation'),
        ),
    ]
