# Generated by Django 4.2.16 on 2025-11-23 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_member_blood_type_member_height_member_weight_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='membercontact',
            constraint=models.UniqueConstraint(fields=('member', 'phone_number'), name='unique_member_contact_phone'),
        ),
    ]
