# Generated by Django 4.2.16 on 2024-12-02 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0007_contactrelation_alter_membercontact_relation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('age_segments', models.ManyToManyField(blank=True, to='crm.agesegment')),
                ('medical_conditions', models.ManyToManyField(blank=True, to='crm.medicalcondition')),
                ('members', models.ManyToManyField(blank=True, to='crm.member')),
            ],
        ),
    ]
