# Generated by Django 4.2.16 on 2025-09-23 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_alter_accessstatus_options_and_more'),
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterField(
            model_name='product',
            name='age_segments',
            field=models.ManyToManyField(blank=True, to='crm.agesegment', verbose_name='Segmentos de edad'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='product',
            name='medical_conditions',
            field=models.ManyToManyField(blank=True, to='crm.medicalcondition', verbose_name='Condiciones de salud'),
        ),
        migrations.AlterField(
            model_name='product',
            name='members',
            field=models.ManyToManyField(blank=True, to='crm.member', verbose_name='Miembros'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
