# Generated by Django 4.2.16 on 2025-09-23 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_alter_product_options_alter_product_age_segments_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
