# Generated by Django 4.2.16 on 2025-10-03 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_alter_accessstatus_options_and_more'),
        ('academy', '0003_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='age_segments',
            field=models.ManyToManyField(blank=True, to='crm.agesegment', verbose_name='Age Segments'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='medical_conditions',
            field=models.ManyToManyField(blank=True, to='crm.medicalcondition', verbose_name='Health Conditions'),
        ),
        migrations.AlterField(
            model_name='product',
            name='members',
            field=models.ManyToManyField(blank=True, to='crm.member', verbose_name='Members'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
