# Generated by Django 4.2.16 on 2025-11-23 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_member_blood_type_member_height_member_weight_and_more'),
        ('academy', '0003_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='members',
        ),
        migrations.CreateModel(
            name='AcademyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='academy.instructor')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academy_profile', to='crm.member')),
            ],
        ),
    ]
