# Generated by Django 4.2.16 on 2025-11-23 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_instructor_remove_product_members_academyprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='academyprofile',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='academy.product'),
        ),
    ]
