# Generated by Django 4.2.16 on 2025-11-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_academyprofile_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='academyprofile',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora fin'),
        ),
        migrations.AddField(
            model_name='academyprofile',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora inicio'),
        ),
    ]
